const fs = require('fs');
const path = require('path');

const envFile = path.resolve(__dirname, '../.env.local');
const outFile = path.resolve(__dirname, '../src/environments/env.config.ts');

const vars = {};

if (fs.existsSync(envFile)) {
  const lines = fs.readFileSync(envFile, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    vars[key] = value;
  }
} else {
  console.warn('[generate-env] .env.local not found — using empty config');
}

// Also read from process.env (Vercel / CI inject env vars this way)
const apiUrl = vars['NG_APP_API_URL'] || vars['VITE_API_URL']
            || process.env['NG_APP_API_URL'] || process.env['VITE_API_URL'] || '';

if (!apiUrl) {
  console.error('[generate-env] ERROR: NG_APP_API_URL is not set. Add it to .env.local or Vercel environment variables.');
  process.exit(1);
}

const content = `// Auto-generated by scripts/generate-env.js — do not edit manually
export const envConfig = {
  apiUrl: '${apiUrl}',
};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, content, 'utf-8');
console.log('[generate-env] Generated src/environments/env.config.ts');
